services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    # 首次使用先执行: cp docker.env.example docker.env 并填写 SECRET_KEY / UTILS_SECRET
    env_file: ./docker.env
    ports:  
      - '8080:3000'  
    volumes:  
      - storage-data:/var/lib/outline/data  
    depends_on:  
      - postgres  
      - redis  

  redis:  
    image: redis  
    env_file: ./docker.env  
    expose:  
      - "6379"  
    volumes:  
      - ./redis.conf:/redis.conf  
    command: ["redis-server", "/redis.conf"]  
    healthcheck:  
      test: ["CMD", "redis-cli", "ping"]  
      interval: 10s  
      timeout: 30s  
      retries: 3  
  
  postgres:  
    image: postgres:18  
    env_file: ./docker.env  
    expose:  
      - "5432"  
    volumes:  
      - database-data:/var/lib/postgresql  
    healthcheck:  
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]  
      interval: 30s  
      timeout: 20s  
      retries: 3  
    environment:  
      POSTGRES_USER: 'user'  
      POSTGRES_PASSWORD: 'pass'  
      POSTGRES_DB: 'outline'  
  
volumes:
  https-portal-data:  
  storage-data:  
  database-data:
